import os
import glob

Decider('MD5-timestamp')

CACHE_DIR = ARGUMENTS.get('CACHE_DIR', '/tmp/scons_cache_dir')
DEBUG = ARGUMENTS.get('DEBUG', '0')
NDEBUG   = ARGUMENTS.get('NDEBUG', '0')
GCC = ARGUMENTS.get('GCC', '0')

CacheDir(CACHE_DIR)

wasmdasm = '../bin/wasmdasm'
libSources = '../sources/c/libwasm.c'

gcc = Environment(CC='gcc',
                  CXX='g++')

if DEBUG == '1':
    gcc.Append(CCFLAGS=' -g')
else:
    gcc.Append(CCFLAGS=' -g -Wall -Wno-unused -O2 -march=native -fomit-frame-pointer -Wmissing-declarations -Wsign-compare -Wconversion -Wno-sign-conversion -Wold-style-cast -Wno-parentheses -Wno-unused')

if NDEBUG == '1':
    gcc.Append(CCFLAGS=' -DNDEBUG')

clang = Environment(CC='clang',
                    CXX='clang++')

if DEBUG == '1':
    clang.Append(CCFLAGS=' -g')
else:
    clang.Append(CCFLAGS=' -g -O2 -Wall -Wno-unused -march=native -fomit-frame-pointer -Wmissing-declarations -Wsign-compare -Wconversion -Wno-sign-conversion -Wold-style-cast -Wno-parentheses -Wno-unused-lambda-capture')

if NDEBUG == '1':
    clang.Append(CCFLAGS=' -DNDEBUG')

if GCC == '1':
    compiler=gcc
else:
    compiler=clang

scripts = glob.glob('wast/*')

for source in scripts:
    name = os.path.split(source)[1]
    name = name.replace('.wast', '')

    cName = 'c/' + name + '.c'
    executable = 'exe/' + name
    outName = 'result/' + name

    Command(cName, [source, wasmdasm], wasmdasm + ' ' + source + ' -C ' + cName)

    compiler.Program(executable, cName,
            LIBS=['libwasmc', 'm'], LIBPATH='../lib',
            CPPPATH=['.', '../sources/c'])

    Command(outName, executable, executable + ' 2>' + outName)
